### ISSUE TITLE
github-slug-action - master branch EOL

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/github-slug-action#15]
Due to changes into the branches management, the `master` branch is not longer supported and will be removed in few months (_EOL: 2020-10-25_).

After a search, here is the list of projects who use `master` branch for this action inside their workflows.

* [x] danielr1996/docker-action-multitag#4
* [x] doerfli/feedscraper#93
* [x] patou/liste-envies#97
* [x] kingkool68/testing-github-actions#1
* [x] TardisBank/TardisBank#48
* [x] feinoujc/node-app#1
* [x] dormdev/dormdev#5
* [x] 7mind/izumi-docker#1
* [x] elmerfdz/rebuild-dndc#31
* [x] VladPodilnyk/d4s-example#2
* [x] LuanaFn/avas-denuncia-backend#12
* [x] time-machine-project/requests-for-comments#9
* [x] chiffre-io/push#44
* [x] elmerfdz/docker-traktarr#8
* [x] elmerfdz/docker-statping#15
* [x] yngwi/requests-for-comments_test#6
* [x] jupitermoney/base-images#2
* [x] elmerfdz/docker-bind#5
* [x] zio/izumi-reflect#21
* [x] PlayQ/d4s#48
* [x] doerfli/rss-mock-server#8
* [x] thecodingmachine/workadventure#58
* [x] voxeet/voxeet-uxkit-react#2
* [x] Meemaw/Insight#17
* [x] kingkool68/wordpress-child-themes#25

**Comment by Ameausoone** [comment]
danielr1996/docker-action-multitag#4 => fixed
VladPodilnyk/d4s-example#2 => fixed

**Comment by rlespinasse** [comment]
The current users of the deprecated `master` branch have some pull requests to fix the removal of the `master` branch.

**Comment by rlespinasse** [comment]
The `master` branch is deleted in order to close this issue.

The documentation about missing `master` branch can be found on the [README of this project](https://github.com/rlespinasse/github-slug-action/blob/v3.x/README.md#missing-master-branch)
